services:
  - type: web
    name: msp-platform-inputiv
    runtime: python
    buildCommand: pip install -r requirements.txt && curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && apt-get install -y nodejs && npm install && apt-get update && apt-get install -y fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libatspi2.0-0 libcups2 libdbus-1-3 libdrm2 libgbm1 libgtk-3-0 libnspr4 libnss3 libwayland-client0 libxcomposite1 libxdamage1 libxfixes3 libxkbcommon0 libxrandr2 xdg-utils
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8011
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
